credentials:
  usernames:
    admin:
      email: admin@suaempresa.com
      name: Administrador
      password: "$2b$12$ynrB5U3wHR1rGERXp8S1YeB16fdGV4YcW.L32/oz/lmmlhAcoCZIm"

    sup_capital:
      email: supervisor.capital@suaempresa.com
      name: Supervisor Capital
      password: "$2b$12$/kaqUyO1Ml1WaSrYNv9EQeSE8kvT1DTutXtH7RIGtxIhdhP1jiyYW"

    sup_metro:
      email: supervisor.metro@suaempresa.com
      name: Supervisor Metropolitan
      password: "$2b$12$K/KJHVgk4a3ULAXQfGRUlu.fBbJXNWQBIavOB2QFH8hUwXq3muCtS"

    sup_country:
      email: supervisor.country@suaempresa.com
      name: Supervisor Countryside
      password: "$2b$12$ZfzG0WJHdqEalCefveCNAuQ4Kx3UhTth3GbIJf1tx069kKUfBtGTG"

    sup_geral:
      email: supervisor.geral@suaempresa.com
      name: Supervisor Geral
      password: "$2b$12$PlKJK4xL6MaH4YcYQTQTDOuTaRdiIHyToHio754CMW1D1e/fhtxxO"

cookie:
  expiry_days: 7
  key: "expedicao_logistica_chave_2024_xK9m"
  name: "expedicao_logistica_cookie"
